DOMAIN = "pcs_agent"
DEFAULT_SERVER = "https://pcs-agent.com"
CONF_SERVER_URL = "server_url"
CONF_USER_ID = "user_id"
CONF_DEVICE_ID = "device_id"
CONF_MAC = "mac_address"
CONF_HA_SECRET = "ha_secret"
CONF_HOST = "host"          # IP LAN dell'agent (local-only)
CONF_PORT = "port"
AGENT_PORT = 8765           # porta HTTP locale agent (/state, comandi)
SCAN_INTERVAL = 5
